// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egmkpldulsfgbxhpjlai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnbWtwbGR1bHNmZ2J4aHBqbGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDYyNTQsImV4cCI6MjA3MjU4MjI1NH0.c1sJxrvrpYQ3j_sq5fNuEPd0C4O3-DFJEMRCZRqNw0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});